java -jar build/compiler.jar --js src/js/about.js --js_output_file src/js/about.min.js
java -jar build/compiler.jar --js src/js/news.js --js_output_file src/js/news.min.js
java -jar build/compiler.jar --js src/js/connected.js --js_output_file src/js/connected.min.js
java -jar build/compiler.jar --js src/js/error.js --js_output_file src/js/error.min.js
java -jar build/compiler.jar --js src/js/main.js --js_output_file src/js/main.min.js
java -jar build/compiler.jar --js src/js/models.js --js_output_file src/js/models.min.js
java -jar build/compiler.jar --js src/js/photos.js --js_output_file src/js/photos.min.js
java -jar build/compiler.jar --js src/js/photoupload.js --js_output_file src/js/photoupload.min.js
java -jar build/compiler.jar --js src/js/podcast.js --js_output_file src/js/podcast.min.js
java -jar build/compiler.jar --js src/js/utils.js --js_output_file src/js/utils.min.js
java -jar build/compiler.jar --js src/js/video.js --js_output_file src/js/video.min.js
java -jar build/compiler.jar --js src/js/viewmanager.js --js_output_file src/js/viewmanager.min.js
java -jar build/compiler.jar --js src/js/settings.js --js_output_file src/js/settings.min.js
